In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("../..//VISIR-2_v6/__data/harbours/harbours_DB.csv")
df.head()

  harb_code        lat        lon name_IT             name_HR link
0     AEAJM  25.416667  55.433333     NaN               Ajman  NaN
1     AEAUH  24.500000  54.333333     NaN            Abu Zaby  NaN
2     AEDAS  25.150000  52.866667     NaN         Jazirat Das  NaN
3     AEDXB  25.277540  55.293780   Dubai               Dubai  NaN
4     AEFAT  25.583333  54.416667     NaN  Fateh Oil Terminal  NaN

In [17]:
scandic_country_codes = ["NO", "SE", "DK", "FI", "IS", "FO"]
df_sc = df[df["harb_code"].str[:2].isin(scandic_country_codes)]
df_sc.shape

(342, 6)

In [18]:
df_sc.head()

    harb_code        lat        lon name_IT       name_HR link
613     DKAAB  55.050000   9.433333     NaN        Abenra  NaN
614     DKAAL  57.050000   9.933333     NaN        Alborg  NaN
615     DKAAR  56.150000  10.216667     NaN         Arhus  NaN
616     DKASN  55.266667   9.883333     NaN        Assens  NaN
617     DKAUB  54.950000   9.866667     NaN  Augustenborg  NaN

In [20]:
df_sc.to_csv('scandinavia_port_codes.csv')

In [21]:
df_sc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 342 entries, 613 to 2517
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   harb_code  342 non-null    object
 1   lat        342 non-null    float64
 2   lon        342 non-null    float64
 3   name_IT    0 non-null      object
 4   name_HR    342 non-null    object
 5   link       0 non-null      object
dtypes: float64(2), object(4)
memory usage: 18.7+ KB